### ISSUE TITLE
Periodic timers are broken

### ISSUE THREAD

**Issue by WebFreak001** [vibe-d/vibe-core#104]
```d
import vibe.core.core;
import vibe.core.log;
import core.time;

void main()
{
    runTask({ while(true) sleep(1.seconds); });

    setTimer(2.seconds, delegate() {
	    import std.datetime;
	    logInfo("The time is: %s", Clock.currTime());
    }, true);

    runApplication();
}
```

Literally the example for setTimer doesn't work, createTimer & rearm doesn't work either.

It only fires once and not periodically.

**Comment by yazd** [comment]
As a workaround, keep whatever `setTimer` returns in a variable that doesn't get destructed and it will work.
I believe the problem is that the reference count is decremented and the timer is invalidated even though it is a periodic timer. But I still can't wrap my head around all of the logic around timers and how the reference counts are calculated in eventcore and vibe-core.
