### ISSUE TITLE
timer runs on main task

### ISSUE THREAD

**Issue by WebFreak001** [vibe-d/vibe-core#125]
```d
import core.time;

import vibe.core.log;
import vibe.core.core;
import vibe.core.sync;

void main()
{
	InterruptibleTaskCondition cond = new InterruptibleTaskCondition(
			cast(Lockable) new InterruptibleTaskMutex());

	setTimer(1.seconds, {
		auto m = cond.mutex;
		m.lock();
		scope (exit)
			m.unlock();
		cond.wait();
	});

	while (true)
	{
		logInfo("log...");
		sleep(500.msecs);
	}
}
```
this will log `log...` twice and then hang forever, even though the condition and the mutex are TaskCondition and TaskCondition, so they shouldn't hang up other tasks. But you can see if you add a log with Task.getThis that the timer starts in `----`, so it hangs all the code. It even hangs the log function if you wrap the whole `while (true)` in a `runTask` and call runEventLoop afterwards

**Comment by s-ludwig** [comment]
This is an interesting problem that emerged from a semantic change for timer callbacks a while back. Before the change, the timer callback got invoked within a newly started task. Now it's called directly from the event loop instead.

What happens here is that the `sleep` is still waiting when `cond.wait()` is called, effectively creating two concurrent paths of execution, but without a task/fiber being involved. Since this is not possible, because there is just a single stack, the original path (`sleep`) is going to stay hibernated until the second nested one is done (never in this case).

I can currently see two possibilities to solve this:

1. Revert back to starting a task for timer callbacks - I'd really like to avoid that, tough, because this was an important optimization in a timer-heavy application

2. Use a `yieldLock()` before invoking the timer callback and improve the documentation. I'd favor this, although it has the drawback that `cond.wait()` would then throw the generic error "May not yield within an active yieldLock()!" without further explanation (although the call stack would show that this is a timer callback).

**Comment by s-ludwig** [comment]
I've created a PR for the latter: #126

**Comment by s-ludwig** [comment]
Hm, good point... maybe reverting the standard `setTimer`/`createTimer` to use tasks and defining new ones is the right way to go after all. It's a breaking change anyway, so otherwise `2.0.0` would be the right version now.

**Comment by s-ludwig** [comment]
Updated the pull request.
