### ISSUE TITLE
Ability to create TCPConnection from native file descriptor

### ISSUE THREAD

**Issue by tchaloupka** [vibe-d/vibe-core#151]
This is more a question or improvement than bug (POSIX only in mind).

We are in need to create some subprocesses via `fork()/exec()` which need to use some communication channel between them.
We're planning to use something like `socketpair(AF_UNIX, SOCK_STREAM | SOCK_NONBLOCK, 0, fd)` for that. But currently, there is no way to create the `TCPConnection` from the raw FD to be able to use it in normal vibe-d app.

What I've found is that this could probably work:
```D
auto ssfd = eventDriver.sockets.adoptStream(fd);
auto con = TCPConnection(ssfd, new RefAddress());
```

But that `TCPConnection` constructor is currently private.
Only possible way now seems to be using the `eventDriver.sockets` methods directly. But we would rather not to replicate what is already working in `vibe-core`.

Should the use of `TCPConnection` work for this case? Can I make a PR to enable the constructor to be called externally?

Thanks!

**Comment by s-ludwig** [comment]
It should be a factory function instead of making the constructor itself public, but other than that this sounds fine. I'd maybe already call this `createStreamSocketFromDescriptor` instead of `createTCPConnectionFromDescriptor`, because the existing functionality is going to be renamed to "stream socket" instead of "TCP connection" anyway.
