### ISSUE TITLE
runEventLoop fails to exit even when receiving signal

### ISSUE THREAD

**Issue by schveiguy** [vibe-d/vibe-core#205]
On my Linux system (linux mint 19), I install a vanilla vibe.d server. Run it, and kill it with ctrl-c. I get a message that the server is shutting down, and get back the command prompt.

But the server didn't shut down, it's still running. And holding onto the listening socket. Turns out it doesn't exit the event loop. This is new since 1.9.0. 1.8.1 does not have this problem.

Attached is a sample log from my system.
[badvibe.txt](https://github.com/vibe-d/vibe-core/files/4462864/badvibe.txt)

**Comment by Kozzi11** [comment]
You can fix it for now by define VibeHighEventPriority version

**Comment by jamesragray** [comment]
How do you define VibeHighEventPriority version?

**Comment by Geod24** [comment]
In dub.json:
```
"versions": [ "VibeHighEventPriority" ]
```

**Comment by schveiguy** [comment]
@Kozzi11 are there any negative effects to expect from that version definition? I'm going to try it, as I'm running into issues with 1.8.1.

**Comment by Kozzi11** [comment]
@schveiguy  Everything works ok for me

**Comment by Robert-M-Muench** [comment]
I have the same problem on OSX.

**Comment by s-ludwig** [comment]
With eventcore 0.9.11 this should now be  fixed (works for me at least).

macOS also works when building with the `kqueue` configuration, but still fails to quit with `cfrunloop`, because AFAICS there is no way to make `CFRunLoopRunInMode` (or some other equivalent API) exit after a signal. I'm also not aware of something similar to signalfd on macOS, so I'm not sure whether this can be made to work at all (disclaimer: I'm not a mac expert).

**Comment by schveiguy** [comment]
I can confirm, my test vanilla vibe server works when I update the dependency! If I create a new vibe-d server, also works.

Thanks!
