### ISSUE TITLE
sendCompat & receiveCompat

### ISSUE THREAD

**Issue by WebFreak001** [vibe-d/vibe-core#63]
Any plans to bring back sendCompat and receiveCompat in vibe.core.concurrency? I don't know what to replace them with

**Comment by s-ludwig** [comment]
The idea is that `std.concurrency` fully replaces the custom implementation, since the integration works properly now. You should be able to switch to them by using `task.tid` as the target, or did you try that already?

**Comment by WebFreak001** [comment]
oh ok, seems like I need to put `@trusted` around everything then to make it work with `@safe` vibe.d

**Comment by WebFreak001** [comment]
it's pretty confusing not having these symbols too when being used to them and also still seeing them on the vibe docs but not knowing that the project uses vibe-core, maybe add a deprecated isWeaklyIsolated `@trusted` compatSend wrapper?

**Comment by s-ludwig** [comment]
I wanted to to take the opportunity to make some smaller breaking changes in the vibe-core transition to clean up, so I'd really like to avoid re-introducing them. Maybe a little "undead"-like package would make sense?

But at least I'll switch the documentation to be generated from vibe-core for the next release. They will need some changes later anyway, so that the individual libraries appear with their respective versions instead of just the main vibe.d versions.

**Comment by s-ludwig** [comment]
Created: https://github.com/vibe-d/vibe-compat

**Comment by WebFreak001** [comment]
cool, thanks!
